FROM registry.svc.ci.openshift.org/openshift/release:golang-1.10 AS builder
WORKDIR /go/src/github.com/coredns/coredns
COPY . .
RUN go build -o coredns .

FROM registry.svc.ci.openshift.org/openshift/origin-v4.0:base
COPY --from=builder /go/src/github.com/coredns/coredns/coredns /usr/bin/coredns
